"""update_job_descriptions_table_p7

Revision ID: 86122aacfc29
Revises: b251d25bda19
Create Date: 2026-06-13 17:07:39.895327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86122aacfc29'
down_revision: Union[str, Sequence[str], None] = 'b251d25bda19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('raw_jd', sa.Text(), nullable=False))
    op.add_column('job_descriptions', sa.Column('parsed_jd', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_descriptions', sa.Column('job_title', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('industry', sa.Text(), nullable=True))
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.drop_column('job_descriptions', 'jd_text')
    op.drop_column('job_descriptions', 'parsed_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('job_descriptions', sa.Column('jd_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_column('job_descriptions', 'industry')
    op.drop_column('job_descriptions', 'job_title')
    op.drop_column('job_descriptions', 'parsed_jd')
    op.drop_column('job_descriptions', 'raw_jd')
    # ### end Alembic commands ###
