"""add_resume_templates_table

Revision ID: b251d25bda19
Revises: d3a07effee0a
Create Date: 2026-06-13 17:03:58.240644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b251d25bda19'
down_revision: Union[str, Sequence[str], None] = 'd3a07effee0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.Column('layout_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['uploaded_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_templates_resume_id'), 'resume_templates', ['resume_id'], unique=True)
    op.create_index(op.f('ix_resume_templates_user_id'), 'resume_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_templates_user_id'), table_name='resume_templates')
    op.drop_index(op.f('ix_resume_templates_resume_id'), table_name='resume_templates')
    op.drop_table('resume_templates')
    # ### end Alembic commands ###
