"""add_job_intelligence_columns

Revision ID: c49b3ae291c8
Revises: 86122aacfc29
Create Date: 2026-06-13 17:22:54.229949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49b3ae291c8'
down_revision: Union[str, Sequence[str], None] = '86122aacfc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('job_category', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('department', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('seniority_level', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'confidence_score')
    op.drop_column('job_descriptions', 'seniority_level')
    op.drop_column('job_descriptions', 'department')
    op.drop_column('job_descriptions', 'job_category')
    # ### end Alembic commands ###
