"""Add master_resume_profiles table

Revision ID: d3a07effee0a
Revises: 976908c0632a
Create Date: 2026-06-13 16:33:16.147338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a07effee0a'
down_revision: Union[str, Sequence[str], None] = '976908c0632a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_resume_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('master_resume_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsing_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['uploaded_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_resume_profiles_resume_id'), 'master_resume_profiles', ['resume_id'], unique=True)
    op.create_index(op.f('ix_master_resume_profiles_user_id'), 'master_resume_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_resume_profiles_user_id'), table_name='master_resume_profiles')
    op.drop_index(op.f('ix_master_resume_profiles_resume_id'), table_name='master_resume_profiles')
    op.drop_table('master_resume_profiles')
    # ### end Alembic commands ###
