"""add template_css to resume_templates

Revision ID: f5958405a164
Revises: c49b3ae291c8
Create Date: 2026-06-14 12:43:51.040136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5958405a164'
down_revision: Union[str, Sequence[str], None] = 'c49b3ae291c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevant_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevant_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('project_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('certification_score', sa.Float(), nullable=True),
    sa.Column('project_rankings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching_confidence', sa.Float(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['uploaded_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analysis_reports_job_id'), 'gap_analysis_reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_reports_resume_id'), 'gap_analysis_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_reports_user_id'), 'gap_analysis_reports', ['user_id'], unique=False)
    op.create_table('optimized_resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('optimized_resume_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimization_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['uploaded_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimized_resumes_job_id'), 'optimized_resumes', ['job_id'], unique=False)
    op.create_index(op.f('ix_optimized_resumes_resume_id'), 'optimized_resumes', ['resume_id'], unique=False)
    op.create_index(op.f('ix_optimized_resumes_user_id'), 'optimized_resumes', ['user_id'], unique=False)
    op.add_column('generated_resumes', sa.Column('resume_id', sa.UUID(), nullable=False))
    op.add_column('generated_resumes', sa.Column('optimized_resume_id', sa.UUID(), nullable=False))
    op.add_column('generated_resumes', sa.Column('html_url', sa.Text(), nullable=True))
    op.add_column('generated_resumes', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('generated_resumes', sa.Column('is_one_page', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'generated_resumes', 'uploaded_resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'generated_resumes', 'optimized_resumes', ['optimized_resume_id'], ['id'])
    op.drop_column('generated_resumes', 'resume_json')
    op.drop_column('generated_resumes', 'ats_score')
    op.add_column('resume_templates', sa.Column('template_css', sa.Text(), nullable=True))
    op.add_column('resume_templates', sa.Column('hyperlinks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_templates', 'hyperlinks')
    op.drop_column('resume_templates', 'template_css')
    op.add_column('generated_resumes', sa.Column('ats_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('generated_resumes', sa.Column('resume_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'generated_resumes', type_='foreignkey')
    op.drop_constraint(None, 'generated_resumes', type_='foreignkey')
    op.drop_column('generated_resumes', 'is_one_page')
    op.drop_column('generated_resumes', 'page_count')
    op.drop_column('generated_resumes', 'html_url')
    op.drop_column('generated_resumes', 'optimized_resume_id')
    op.drop_column('generated_resumes', 'resume_id')
    op.drop_index(op.f('ix_optimized_resumes_user_id'), table_name='optimized_resumes')
    op.drop_index(op.f('ix_optimized_resumes_resume_id'), table_name='optimized_resumes')
    op.drop_index(op.f('ix_optimized_resumes_job_id'), table_name='optimized_resumes')
    op.drop_table('optimized_resumes')
    op.drop_index(op.f('ix_gap_analysis_reports_user_id'), table_name='gap_analysis_reports')
    op.drop_index(op.f('ix_gap_analysis_reports_resume_id'), table_name='gap_analysis_reports')
    op.drop_index(op.f('ix_gap_analysis_reports_job_id'), table_name='gap_analysis_reports')
    op.drop_table('gap_analysis_reports')
    # ### end Alembic commands ###
